### PR TITLE
Candidate to release

### PR DESCRIPTION
**Pull request by schernolyas**
the PR contains:
1. restored changes in core tests
2. refactoring of classes in OrientDB module
3. add javadoc of classes in OrientDB module

### CODE REVIEW

**Comment by DavideD** [comment]
Thanks @SergeyChernolyas the PR is fine, but the project evolved and I need to solve conflicts between the branch we are working and master. I'm not sure when I will start to do it as we have other priorities at the moment.

I think the best course of action at the moment would be to focus on some other smaller issues.
I'll let you know as soon as I fix the problems in the OrientDB branch.

**Comment by schernolyas** [comment]
Hi @DavideD !

What is your progress with fixing the problems in the OrientDB branch?

**Comment by DavideD** [comment]
Hi @schernolyas,
we were busy preparing the release for OGM, with Neo4j remote and (soon) HotRod. I'll work on this this week.

**Comment by schernolyas** [comment]
Hi @DavideD !

Okey ;-(  Let me know when You are ready for OrientDB.

Good luck!

**Comment by DavideD** [comment]
Hey @schernolyas, is this suppose to work with a remote datastore?
I'm asking because if I set the type to remote it does not work.

Let me know and please don't try to fix it, I'm rebasing my branch with these changes and the latest OGM master and I'll push force the branch when I'm done

**Comment by schernolyas** [comment]
Hi @DavideD !

I am glad to see You :-)

As I remember, my implementation works with remote datastore. I tested it 2-3 months ago. I will retest it and upgrade orientdb version after I get your resolution.

For fix something, I am waiting your resolution:-)

**Comment by schernolyas** [comment]
Hi @DavideD 
Working with remote database was supported.
See https://github.com/schernolyas/hibernate-ogm/blob/core_tests3/orientdb/src/main/java/org/hibernate/ogm/datastore/orientdb/impl/OrientDBDatastoreProvider.java

**Comment by DavideD** [comment]
It doesn't work. when I set REMOTE as property I have an error.



On Sun, Oct 16, 2016 at 1:50 PM, Sergey Chernolyas <notifications@github.com

**Comment by DavideD** [comment]
@schernolyas It seems that when I launch a test like BuiltInTypeTest or CRUDTest in remote mode the DB is not cleaned at the end. Therefore, every time I finished running a test I need to clean up the db.
In remote mode I also need to create the db manually and OGM does not seem to do that.

Could you create a new branch starting from my branch `OGM-855-OrientDB` and make sure that when a the test is finished in REMOTE that db is dropped? At the moment it seems it only works when using the in memory database and this make it hard to check what has been created in the db. The db should also be created if the property `hibernate.ogm.datastore.create_database` is set to true.

Check the OrientDBTest class and once the test creates the database and drop it properly, send me another PR please.

Thanks,
Davide

**Comment by schernolyas** [comment]
Hi @DavideD !
I glad that You return to the project :-)
I created new branch that based on your. (commands: 1) git checkout DavideD/OGM-855-OrientDB 2) git checkout -b fix_remote_mode)

**Pull request closed without merging**
